### ISSUE TITLE
Wczytywanie w plików

### ISSUE THREAD

**Issue by jakpor** [jakpor/Trasy_biegaczy#1]
Nie działa, chociaż powinno.
Aktualnie wypisuje dokladnie to samo co wczytuje, lecz niestety nei wyświetla. Może jegdzieś jest dzielenie przez 0?

**Comment by Zanet** [comment]
Teraz ładnie czyta. Jak nie zmienię, źródła plików to rysuje mi same linie ale problem wydaje się być rozwiązany. :)
